version: "3"

services:
  mariadb:
    restart: always

  php:
    restart: always
    environment:
      ARCHIVIO_ENV: "live"
    volumes:
      - ../backup_migrate/archiviostorico:/var/backup/archivio

  nginx:
    restart: always
    ports:
     - "8000:80"

  varnish:
    restart: always
    ports:
      - "6081:6081"

  solr:
    restart: always

  redis:
    restart: always
