version: "3"

services:
  mariadb:
    restart: always
  
  php:
    restart: always
    environment:
      ARCHIVIO_ENV: "live"

  nginx:
    restart: always
    ports:
     - "8000:80"

  solr:
    restart: always 
