layout_builder_dialog_control.settings:
  type: config_object
  label: 'Layout Builder Dialog Control Settings'
  mapping:
    layout_builder_contextual_links:
      type: sequence
      label: 'Contextual links'
      sequence:
        type: config_object
        label: 'Contextual link'
        mapping:
          dialog_type:
            type: string
            label: 'Dialog type'
          route_name:
            type: string
            label: 'Route name'

