ente_appartenenza: 'Università degli Studi di Cagliari'
_core:
  default_config_hash: sUXbAWjCCUm114hgcUWPGMzCwtGxUBY_DWXKsEH6JZ4
features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
logo:
  use_default: false
  path: 'public://logouniv800_0.gif'
favicon:
  use_default: true
