status: 1
pattern: '[node:field_primo_cognome] [node:field_secondo_cognome] [node:field_primo_nome] [node:field_secondo_nome] [node:field_terzo_nome]'
escape: false
dependencies:
  config:
    - node.type.persona
