status: 1
pattern: 'Carriera [node:field_tipologia_carriera] ([node:nid]) [node:field_persona:entity:title] [node:field_data_inizio_carriera] [node:field_facolta]'
escape: false
dependencies:
  config:
    - node.type.carriera
