module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  archivio_cer: 0
  archivio_utils: 0
  auto_entitylabel: 0
  automated_cron: 0
  bg_image_formatter: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  coffee: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_split: 0
  contact: 0
  contextual: 0
  csv_serialization: 0
  ctools: 0
  datetime: 0
  dblog: 0
  diff: 0
  editor: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  facets: 0
  facets_summary: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  geofield_map: 0
  geofield_map_extras: 0
  help: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  language: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_views: 0
  link: 0
  locale: 0
  media: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  metatag_open_graph: 0
  metatag_views: 0
  module_filter: 0
  node: 0
  options: 0
  override_node_options: 0
  owlcarousel2: 0
  path: 0
  path_alias: 0
  rabbit_hole: 0
  rdf: 0
  readonly_field_widget: 0
  redis: 0
  reroute_email: 0
  responsive_image: 0
  rest: 0
  rh_media: 0
  rh_node: 0
  rh_taxonomy: 0
  schema_metatag: 0
  search_api: 0
  search_api_solr: 0
  security_review: 0
  serialization: 0
  shortcut: 0
  simple_sitemap: 0
  smtp: 0
  switch_page_theme: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  toolbar_menu: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  ui_patterns: 0
  ui_patterns_field_group: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_views: 0
  ultimate_cron: 0
  update: 0
  user: 0
  vde_drush: 0
  view_unpublished: 0
  views_bulk_operations: 0
  views_data_export: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  claro: 0
  bootstrap_italia: 0
  archivio: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: it
